### ISSUE TITLE
Status 525

### ISSUE THREAD

**Issue by limex** [erik/strava-heatmap-proxy#2]
Hi Eric,
first: Thanks for your work, it could solve my issue to get Heatmaps again to QMapShack.

But: I tried first the easy way without success. And then the Manual way. 
In Manual way from my localhost dev Env, I realized that I get Error 525 from Strava.
Could it be that this is linked to https://httpcodes.fyi/525/?

Is it working for you?

BR Günther

**Comment by erik** [comment]
Hey Günther, thanks for reporting.

I can't replicate this error for myself or by peeking at a few other forks of this repo.

Fairly sure you're right about the root cause, this is almost certainly due to the connection between the CloudFlare worker and Strava failing.

Is there any more information you can provide? If you go to the workers console, can you find any logging or error messages?

And just to check, you do have a Strava Premium membership, right?

**Comment by limex** [comment]
Hey Eric,
I also have Strava Premium.
I see the strava cookies in a console log.

I also think to code is ok. 
Because when I run i.e. https://strava-heatmap-proxy.limex.workers.dev/global/orange/11/351/817.png from the Cloudflare Page "Workers -> /strava-heatmap-proxy -> Resources -> Quick Edit Button -> Send Button" then I get the png tile from Los Angeles. The index page https://strava-heatmap-proxy.limex.workers.dev also works.

But if I use my local browser to go directly to https://strava-heatmap-proxy.limex.workers.dev/global/orange/11/351/817.png then I get an "This page isn’t working. If the problem continues, contact the site owner. HTTP ERROR 525".
While https://strava-heatmap-proxy.limex.workers.dev shows the index page.

What is going on here. Is there any additional route I have to set in cloudflare?

**Comment by erik** [comment]
Unfortunately I'm not sure where the problem could be. Wildly guessing - you may have been heavily throttled by Strava if you requested an abnormally high number of tiles or published the tiles for others to use.

I tried creating a new worker from scratch following only the README, and was successfully able to load tiles. Unless there's some account-wide CloudFlare configuration I'm not aware of, nothing outside of the README steps should be required.

Maybe try deleting and recreating the worker?

If that doesn't work, you might need to modify the server code to print out some more debug information, or ask around in a CloudFlare support channel. Please let me know if there's anything we need to change in this repo when you find the root cause.

**Comment by erik** [comment]
Closing out old issues - feel free top reopen if still relevant!
